#!/bin/bash
echo "=== Slot Monitoring System Verification ==="
echo -n "1. tsx and server running? "
pgrep -f "tsx src/server.ts" > /dev/null && echo "✅" || echo "❌ (run: ./restore_and_run.sh)"
echo -n "2. api_watcher running? (optional) "
pgrep -f "api_watcher.py" > /dev/null && echo "✅" || echo "⚠️ Not needed (monitor uses internal loop)"
echo -n "3. Telegram 409 conflict? "
journalctl --user -u visa-agent -n 20 2>/dev/null | grep -q "409" && echo "⚠️ Still present" || echo "✅ Resolved"
echo -n "4. Network reachable (google)? "
curl -s -o /dev/null -w "%{http_code}" https://google.com | grep -q "200\|301\|302" && echo "✅" || echo "❌"
echo -n "5. Config file valid? "
python3 -c "import yaml; yaml.safe_load(open('config.yaml'))" 2>/dev/null && echo "✅" || echo "❌"
echo -n "6. Browser profile exists? "
[ -d "/home/samsepi0l/.config/google-chrome/tls-work" ] && echo "✅" || echo "❌"
echo "=== To see live logs: tmux attach -t visa ==="
